### ISSUE TITLE
⌘ + O: dark mode 👍, light mode 👎 

### ISSUE THREAD

**Issue by DutchPete** [jdanielmourao/obsidian-sanctum#10]
When I press ⌘ + O to open a new note, there is a list of title and with the ↓ or ↑ key you can move the highlight bar down or up. In dark mode the bar is visible and usable, in light mode the highlight bar is not there.

I am using 0.2.1.

**Comment by jdanielmourao** [comment]
Well, that is incredibly frustrating. It's set to `color-hover`, which depends on if it's dark or light theme, but should work either way...
Could you try adding this as a snippet and see if it gets the job done?
```
.suggestion-item.is-selected {
    background-color: var(--color-hover);
}
```
Add `!important` if necessary.

**Comment by DutchPete** [comment]
Nope, that does not work, even with `!important`.

Before 0.2.1 I used this:

```css
theme-light
.suggestion-item {
    font-size: 14px;
    background-color: var(--color-grey-20);
    font-family: Space Mono;
}

theme-light
.suggestion-item.is-selected {
    font-size: 16px;
    background-color: white !important;
}

theme-dark
.suggestion-item {
    font-size: 14px;
    background-color: var(--color-grey-50);
    font-family: Space Mono;
}

theme-dark
.suggestion-item.is-selected {
    font-size: 16px;
    background-color: black;
}
```

which is like yours except for those extra lines. With 0.2.1 I disabled it because the highlight bar was working out-of-the-box, until I closed and relaunched Obs.
