### ISSUE TITLE
[BUG] [LP] `!important` prevent change font-family heading with cssclass

### ISSUE THREAD

**Issue by Mara-Li** [jdanielmourao/obsidian-sanctum#126]
**Describe the bug**

I can't "manually" change the font of heading with a cssclass because of an `!important` : 
```css
.cm-s-obsidian .cm-header-1,.cm-s-obsidian .cm-header-2,.cm-s-obsidian .cm-header-3,.cm-s-obsidian .cm-header-4,.cm-s-obsidian .cm-header-5,.cm-s-obsidian .cm-header-6,.cm-s-obsidian .HyperMD-header-1,.cm-s-obsidian .HyperMD-header-2,.cm-s-obsidian .HyperMD-header-3,.cm-s-obsidian .HyperMD-header-4,.cm-s-obsidian .HyperMD-header-5,.cm-s-obsidian .HyperMD-header-6{font-family:var(--font-heading-editor)!important}
```

![image](https://user-images.githubusercontent.com/30244939/150739976-503851de-62b8-48b7-9b7c-2c9aecc5cfc4.png)
![image](https://user-images.githubusercontent.com/30244939/150740003-37ac701c-8a11-4346-9896-9db87ef1eef1.png)

**To Reproduce**
Steps to reproduce the behavior (this is an example):
1. Create a snippet cssclass with : 
```css
.draft .cm-line,
.draft .markdown-source-view,
.draft .cm-s-obsidian:not(span.cm-comment),
.draft .markdown-preview-view,
.markdown-reading-view .draft,
.draft {
  font-family: 'Fantasque Sans Mono' !important;
}
```
2. Use it in a file.

**Expected behavior**

![image](https://user-images.githubusercontent.com/30244939/150740205-203e93e6-91a4-47b4-beb9-ee07d9f8757c.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/30244939/150740263-dc3d78ff-062e-49fc-8608-c37312e2ce37.png)

**Version [Desktop or Mobile]:**
→ The two version (mobile and desktop LP)

**Editor**
Live Preview CM6 Editor

**Additional context**
Removing the important doesn't seem to be a problem here.

**Comment by jdanielmourao** [comment]
I have removed the `!important` in my dev version of the theme, so it won't be there in the next update. In the meantime, and for reference, you can always try changing the custom property value locally, like so:
```css
.draft .cm-line,
.draft .markdown-source-view,
.draft .cm-s-obsidian:not(span.cm-comment),
.draft .markdown-preview-view,
.markdown-reading-view .draft,
.draft {
    --font-heading-editor: 'Fantasque Sans Mono';
}
```
