### ISSUE TITLE
[IDEA/REQUEST] Support for File Info Plugin

### ISSUE THREAD

**Issue by eleanorkonik** [jdanielmourao/obsidian-sanctum#142]
**Is your feature request related to a problem? Please describe.**

The file info panel is so small I can't read it :( but it has tons of useful information! 

**Describe the solution you'd like**

Increase the font size of whatever that css stuff is? 

**Describe alternatives you've considered**

I can override the css myself using [the snippet on the repo](https://github.com/CattailNu/obsidian-file-info-panel-plugin), I just wanted to let you know about  the issue :) 

**Additional context**

![image](https://user-images.githubusercontent.com/75856959/153624993-e626fec0-9371-4751-b55e-947ac4b23cb7.png)

**Comment by jdanielmourao** [comment]
I've moved this to the "Todo" section of the Roadmap. Will work on adding it in the future. :)

**Comment by jdanielmourao** [comment]
Alright, everything should match the interface font size now. :) You can update!

**Comment by jdanielmourao** [comment]
@eleanorkonik You can use this as a snippet:
```css
:is(.tlfFileInfoTable, .tlfFileInfoTable100) .tlfFileInfoTextArea,
:is(.tlfFileInfoTable, .tlfFileInfoTable100) .tlfFileInfoValue,
:is(.tlfFileInfoTable, .tlfFileInfoTable100) .tlfFileInfoValueNumber,
:is(.tlfFileInfoTable, .tlfFileInfoTable100) .tlfFileInfoLabel,
:is(.tlfFileInfoTable, .tlfFileInfoTable100) .tlfFileInfoButton {
	font-size: 1em;
}

.tlfFileInfoTable,
.tlfFileInfoTable100 {
	border-spacing: 4px;
}
```
