### ISSUE TITLE
Minor layout issue in pinned commands UI

### ISSUE THREAD

**Issue by ekafyi** [jdanielmourao/obsidian-sanctum#16]
The "pin" icon to the left of pinned commands overlaps with the text.

![Screen Shot 2021-10-21 at 19 51 21](https://user-images.githubusercontent.com/6597211/138281207-ee706003-07df-4eac-aa37-2dba8250bf58.png)

It _might_ be due to some other plugins/snippets I use; I'm afraid I don't have the time to check at the moment. I'm just posting it here in case others come across this and looking for a fix.

```css
.suggestion-flair {
	left: 0;
	top: 4px;
	transform: scale(0.75);
}
```

Also feel free to close if you cannot replicate it.

Thanks for the great theme!
