### ISSUE TITLE
CodeMirror plug-in collapse external links

### ISSUE THREAD

**Issue by DutchPete** [jdanielmourao/obsidian-sanctum#3]
version 0.2 Sanctum

The CodeMirror plug-in's *collapse external links* feature does not work at my end. I disabled all my plug-ins and snippets, to no avail.

This is the code I use as a workaround:

```css
div:not(.CodeMirror-activeline) > .CodeMirror-line .cm-string.cm-url:not(.cm-formatting) {
    font-size: 0;
}
div:not(.CodeMirror-activeline) > .CodeMirror-line .cm-string.cm-url:not(.cm-formatting)::after {
    content: '🔗'; /* » */
    font-size: 1rem;
}
```
