### ISSUE TITLE
[BUG] Selection of inline code is not visible in edit mode

### ISSUE THREAD

**Issue by halega** [jdanielmourao/obsidian-sanctum#52]
**Describe the bug**
Selection of code formatted with `` is not visible. If I want to select a part of code, I don't see selection at all.

**To Reproduce**
1. Insert text:
Code: `this is code formatted text`.
2. Try to select it by mouse.

**Expected result**
There's a selection rectangle covered all selected text.

**Actual result**
Selection rectangle isn't visible at code block.

**Screenshots**

![image](https://user-images.githubusercontent.com/35935/143220955-827ebe07-324b-473c-8bfe-858bff78349c.png)

There's no problem in rendered mode:

![image](https://user-images.githubusercontent.com/35935/143221026-140aabfc-2ce5-4115-ab29-20b4157dc720.png)

**Version [Desktop or Mobile]:**
v0.12.19 with latest theme version.

**Additional context**

Comparison with Blue Topaz theme:

![image](https://user-images.githubusercontent.com/35935/143221246-8a4f5644-7138-4316-a15e-c9ae10cb5783.png)

**Comment by jdanielmourao** [comment]
Hello! Thanks for reporting it, I'll work on fixing it in time for next update's release.

**Comment by jdanielmourao** [comment]
Please confirm if the issue has been fixed! :)

**Comment by halega** [comment]
Selection rectangle is still behind white background:

![image](https://user-images.githubusercontent.com/35935/143998112-54511844-604b-4982-9cbe-5e9559168e0f.png)

Now there's just a thin line under the code:

![image](https://user-images.githubusercontent.com/35935/143998353-5958212c-2542-41d0-8af8-2e50ce90ec85.png)

**Comment by jdanielmourao** [comment]
Oh, I see what this is. I don't think it's possible in regular edit mode, unless you assign a background with some transparency, but then you'd lose the contrast between inline code and regular code (besides the color of the text, ofc).
You can try adding the following snippet:
```css
.cm-s-obsidian span.cm-inline-code:not(.cm-formatting):not(.cm-hmd-indented-code):not(.obsidian-search-match-highlight),
span.cm-formatting.cm-formatting-code.cm-inline-code {
	background-color: hsla(var(--hsl-color-primary-w), .5);
}
```
