### ISSUE TITLE
[BUG] Flickering graph analysis plugin pane

### ISSUE THREAD

**Issue by DeutscheGabanna** [jdanielmourao/obsidian-sanctum#72]
**Describe the bug**
If graph analysis pane is installed, it flickers when being used.

**To Reproduce**
1. Install graph analysis pane
2. Open the pane
3. Use it

**Expected behavior**
Buttons and tabs should not flicker.

**Version [Desktop or Mobile]:** win10

**Comment by jdanielmourao** [comment]
The Graph Analysis plugin isn't currently supported by this theme. I took a look at it, and I think you will encounter the same issue in any theme that makes the choice of disabling most of the scrollbars. Having said that, you can try removing that padding, with this snippet:
```css
.workspace-leaf-content .view-content.GA-View div.scrollContainer {
	padding-bottom: 0;
}
```
